# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9dd469616b6d2bfc6ba884793193e487cf47ed03020bd8af9475bad61ad31e021a0405efe530de7684b465ed7f3a2317dd99d91af923822cd40455748d1fb367

test:
  secret_key_base: 868a02c839c43788430eb83a8c65e0a812f64b163642c5fe28c99779bb4cdf17e9747238ffccbb3662e8e4cb8711570c3b5a2031343b5637bcc595478f089d6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
